'use client';

import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Smile, Frown, Meh, Percent, BrainCircuit } from 'lucide-react';
import { useToast } from "@/components/ui/use-toast";

interface AIAnalyticsData {
  comment_sentiment_score: number;
  comment_sentiment_label: string;
  predicted_ctr: number;
  last_analyzed_at: string;
}

interface AIInsightsDashboardProps {
  adId: string;
}

const SentimentIcon = ({ label }: { label: string }) => {
  if (label === 'Positive') return <Smile className="h-10 w-10 text-green-500" />;
  if (label === 'Negative') return <Frown className="h-10 w-10 text-red-500" />;
  return <Meh className="h-10 w-10 text-yellow-500" />;
};

export default function AIInsightsDashboard({ adId }: AIInsightsDashboardProps) {
  const [analytics, setAnalytics] = useState<AIAnalyticsData | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const { toast } = useToast();

  useEffect(() => {
    async function fetchAnalytics() {
      try {
        // This should be a GET request to fetch existing data
        // For simplicity, we'll assume there's an endpoint for it
        // or that it's passed as a prop.
        // Let's stub it for now.
        // const response = await fetch(`/api/ai-analytics?adId=${adId}`);
        // const data = await response.json();
        // setAnalytics(data);
      } catch (error) {
        console.error('Failed to fetch AI analytics', error);
      } finally {
        setIsLoading(false);
      }
    }
    fetchAnalytics();
  }, [adId]);

  const handleRunAnalysis = async () => {
    setIsAnalyzing(true);
    try {
      const response = await fetch('/api/ai-analytics', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ adId }),
      });

      if (!response.ok) {
          throw new Error('Analysis failed to run.');
      }

      const result = await response.json();
      setAnalytics(result.analysis);
      toast({
        title: "Analysis Complete!",
        description: "Your AI-powered insights have been updated.",
      });
    } catch (error) {
      toast({
        title: "Error",
        description: error.message,
        variant: "destructive",
      });
    } finally {
      setIsAnalyzing(false);
    }
  };

  return (
    <Card>
      <CardHeader>
        <div className="flex justify-between items-center">
            <div>
                <CardTitle className="flex items-center"><BrainCircuit className="mr-2 h-5 w-5" /> AI-Powered Insights</CardTitle>
                <CardDescription>Metrics generated by our AI models.</CardDescription>
            </div>
            <Button onClick={handleRunAnalysis} disabled={isAnalyzing}>
                {isAnalyzing ? 'Analyzing...' : 'Run New Analysis'}
            </Button>
        </div>
      </CardHeader>
      <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {isLoading ? (
            <p>Loading insights...</p>
        ) : !analytics ? (
            <p className="col-span-2 text-center">Run an analysis to see your AI insights.</p>
        ) : (
          <>
            <div className="p-4 rounded-lg bg-gray-50 dark:bg-gray-800 text-center">
                <p className="text-sm font-medium text-muted-foreground">Comment Sentiment</p>
                <div className="flex justify-center items-center my-3">
                    <SentimentIcon label={analytics.comment_sentiment_label} />
                </div>
                <p className="text-xl font-bold">{analytics.comment_sentiment_label}</p>
                <p className="text-xs text-muted-foreground">Score: {analytics.comment_sentiment_score.toFixed(3)}</p>
            </div>
            <div className="p-4 rounded-lg bg-gray-50 dark:bg-gray-800 text-center">
                <p className="text-sm font-medium text-muted-foreground">Predicted CTR</p>
                <div className="flex justify-center items-center my-3">
                    <Percent className="h-10 w-10 text-blue-500" />
                </div>
                 <p className="text-xl font-bold">{(analytics.predicted_ctr * 100).toFixed(2)}%</p>
                 <p className="text-xs text-muted-foreground">Based on ad metadata</p>
            </div>
          </>
        )}
      </CardContent>
    </Card>
  );
}
